#!/bin/sh
# flac2mp3 --- Incremental Transcoding of FLAC Files
#
# Author: Haden Pike <haden.pike@gmail.com>
#
# Copyright (c) 2015 Haden Pike
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Using a makefile for this was my first choice
# however, it does not handle whitespace in filenames correctly.

SRCDIR="${PWD}"
DESTDIR="${PWD}"
while getopts ":s:d:" opt; do
    case $opt in
	s) SRCDIR=$OPTARG;;
	d) DESTDIR=$OPTARG;;
	\?) echo "Usage: $0 [-s The source directory] [-d The destination directory]"
	    exit 1;;
    esac
done

if [ ! -d "${SRCDIR}" ]; then
    echo "${SRCDIR} is not a directory."
    exit 1
fi
if [ ! -d "${DESTDIR}" ]; then
    echo "${DESTDIR} is not a directory."
    exit 1
fi

for i in ${SRCDIR}/*.flac; do
    NEW_NAME="${DESTDIR}/`basename "${i}" .flac`.mp3"
    if [ -e "${NEW_NAME}" ]; then
	continue
    else
	ffmpeg -i "${i}" -f mp3 -qscale:a 4 "${NEW_NAME}" || break
    fi
done
